.TH "BuildDeck" 3 "Version 1.0" "Java Solitaire Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BuildDeck
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDeck\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBuildDeck\fP (String suite)"
.br
.ti -1c
.RI "\fBCard\fP \fBplayCard\fP (\fBCard\fP cardIn)"
.br
.ti -1c
.RI "int \fBgetDeckSize\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBDeck\fP
.in +1c
.ti -1c
.RI "void \fBdefineCards\fP ()"
.br
.ti -1c
.RI "void \fBshuffleDeck\fP ()"
.br
.ti -1c
.RI "\fBCard\fP \fBtakeCard\fP ()"
.br
.ti -1c
.RI "void \fBaddCard\fP (\fBCard\fP cardIn)"
.br
.ti -1c
.RI "void \fBrefillDeck\fP (\fBDeck\fP deckIn)"
.br
.ti -1c
.RI "String \fBprintDeck\fP (int line)"
.br
.ti -1c
.RI "String \fBprintTopCard\fP (int line)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBBuildDeck\fP class extends the \fBDeck\fP class and represents one of the 4 'build' decks that the player can place cards on\&. 
.PP
Definition at line \fB5\fP of file \fBBuildDeck\&.java\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BuildDeck\&.BuildDeck (String suite)"
Constructor for the \fBBuildDeck\fP class\&.

.PP
\fBParameters\fP
.RS 4
\fIsuite\fP The suit associated with the deck\&. 
.RE
.PP

.PP
Definition at line \fB15\fP of file \fBBuildDeck\&.java\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int BuildDeck\&.getDeckSize ()"
Method to get the size of the deck\&.

.PP
\fBReturns\fP
.RS 4
The size of the deck\&. 
.RE
.PP

.PP
Definition at line \fB141\fP of file \fBBuildDeck\&.java\fP\&.
.SS "\fBCard\fP BuildDeck\&.playCard (\fBCard\fP cardIn)"
Plays a card into the deck if it matches the associated suit and follows the correct rank order\&.

.PP
\fBParameters\fP
.RS 4
\fIcardIn\fP The card to be played\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The card played, or null if the card was successfully added to the deck\&. 
.RE
.PP

.PP
Definition at line \fB28\fP of file \fBBuildDeck\&.java\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Java Solitaire Project from the source code\&.
