.TH "Card" 3 "Version 1.0" "Java Solitaire Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Card
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCard\fP (String rank, String suit)"
.br
.ti -1c
.RI "String \fBgetRank\fP ()"
.br
.ti -1c
.RI "String \fBgetSuit\fP ()"
.br
.ti -1c
.RI "int \fBgetNumValue\fP ()"
.br
.ti -1c
.RI "Boolean \fBisShown\fP ()"
.br
.ti -1c
.RI "Boolean \fBisUnder\fP ()"
.br
.ti -1c
.RI "void \fBshow\fP ()"
.br
.ti -1c
.RI "void \fBhide\fP ()"
.br
.ti -1c
.RI "void \fBover\fP ()"
.br
.ti -1c
.RI "void \fBunder\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB2\fP of file \fBCard\&.java\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Card\&.Card (String rank, String suit)"
Constructor for the \fBCard\fP class\&.

.PP
\fBParameters\fP
.RS 4
\fIrank\fP The rank of the card\&. 
.br
\fIsuit\fP The suit of the card\&. 
.RE
.PP

.PP
Definition at line \fB15\fP of file \fBCard\&.java\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int Card\&.getNumValue ()"

.PP
Definition at line \fB48\fP of file \fBCard\&.java\fP\&.
.SS "String Card\&.getRank ()"

.PP
Definition at line \fB40\fP of file \fBCard\&.java\fP\&.
.SS "String Card\&.getSuit ()"

.PP
Definition at line \fB44\fP of file \fBCard\&.java\fP\&.
.SS "void Card\&.hide ()"

.PP
Definition at line \fB65\fP of file \fBCard\&.java\fP\&.
.SS "Boolean Card\&.isShown ()"

.PP
Definition at line \fB52\fP of file \fBCard\&.java\fP\&.
.SS "Boolean Card\&.isUnder ()"

.PP
Definition at line \fB56\fP of file \fBCard\&.java\fP\&.
.SS "void Card\&.over ()"

.PP
Definition at line \fB69\fP of file \fBCard\&.java\fP\&.
.SS "void Card\&.show ()"

.PP
Definition at line \fB61\fP of file \fBCard\&.java\fP\&.
.SS "void Card\&.under ()"

.PP
Definition at line \fB73\fP of file \fBCard\&.java\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Java Solitaire Project from the source code\&.
