.TH "DiscardDeck" 3 "Version 1.0" "Java Solitaire Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DiscardDeck
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDeck\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDiscardDeck\fP ()"
.br
.ti -1c
.RI "void \fBaddCards\fP (\fBDeck\fP deckIn)"
.br
.in -1c

Public Member Functions inherited from \fBDeck\fP
.in +1c
.ti -1c
.RI "void \fBdefineCards\fP ()"
.br
.ti -1c
.RI "void \fBshuffleDeck\fP ()"
.br
.ti -1c
.RI "\fBCard\fP \fBtakeCard\fP ()"
.br
.ti -1c
.RI "void \fBaddCard\fP (\fBCard\fP cardIn)"
.br
.ti -1c
.RI "void \fBrefillDeck\fP (\fBDeck\fP deckIn)"
.br
.ti -1c
.RI "String \fBprintDeck\fP (int line)"
.br
.ti -1c
.RI "String \fBprintTopCard\fP (int line)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDiscardDeck\fP class extends \fBDeck\fP and represents the 'draw' pile 
.PP
Definition at line \fB4\fP of file \fBDiscardDeck\&.java\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DiscardDeck\&.DiscardDeck ()"
Constructor for \fBDiscardDeck\fP class 
.PP
Definition at line \fB9\fP of file \fBDiscardDeck\&.java\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void DiscardDeck\&.addCards (\fBDeck\fP deckIn)"
addCards method to add cards to the discard deck from the draw pile\&. 
.PP
\fBParameters\fP
.RS 4
\fIdeckIn\fP The deck object to take the cards from\&. 
.RE
.PP

.PP
Definition at line \fB17\fP of file \fBDiscardDeck\&.java\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Java Solitaire Project from the source code\&.
