.TH "C:/Users/SByers/OneDrive - Analog Devices, Inc/Desktop/java/ScoreSystem.java" 3 "Version 1.0" "Java Solitaire Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/SByers/OneDrive - Analog Devices, Inc/Desktop/java/ScoreSystem.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScoreSystem\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Java Solitaire Project from the source code\&.
